nelmio_cors:
    paths:
        "^/api/":
            allow_origin: ["http://localhost:4100","https://peaceful-escarpment-65444.herokuapp.com"]
            allow_headers: ["X-Custom-Auth","Origin", "Accept", "Content-Type"]
            allow_methods: ["POST", "PUT", "GET", "DELETE", "OPTIONS"]
            max_age: 3600
        "^/":
            allow_credentials: false
            origin_regex: true
            allow_origin: ["http://localhost:4100","https://peaceful-escarpment-65444.herokuapp.com"]
            allow_headers: ["Origin", "Accept", "Content-Type"]
            allow_methods: ["POST", "GET", "DELETE", "PUT", "OPTIONS"]
            max_age: 3600
